name: Auto Add to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    permissions:
      issues: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/lifefinity/projects/3
          github-token: ${{ secrets.PROJECT_TOKEN }}
